### ISSUE TITLE
Kraken Scaling off Base Damage Instead of Total Damage

### ISSUE THREAD

**Issue by 06Kioshi** [Debonairesnake6/LoLItems#28] opened 2023-10-08 01:29 UTC
Loving the mod so far! The only issue I have is with the way Kraken Slayer scales. Scaling it based off of total damage would mean high attack speed characters with low damage as well as slow attack speed damage characters with high damage would both benefit from it. 

I've been messing around with the Jhin mod along with your mod and I've had Kraken since stage 2 and its only done about 900 damage. I picked up I.E. for about 30 seconds and it already out damaged Kraken with a whopping 1500 damage. It doesn't make a whole a lot of sense in my eyes that they're the same tier but I.E. VASTLY out damages Kraken.

Also an effect like the bands and safer spaces showing when my next Kraken shot is going to proc would be nice. As well as a separate damage number in a different color so I can visualize the kind of damage its doing.

I understand it might be a lot to ask and of course this is merely a suggestion. Love what you're doing and keep up the great work :D

**Comment by knightmare013** [comment] 2023-10-08 02:33
i also this it may just be cause the stacking doesn't quite work as intended

**Comment by Debonairesnake6** [comment] 2023-10-08 04:02
I'm glad you're enjoying the mod, and thanks for the feedback! I'll summarize my response to your comments:

- Scaling off of Total Damage would be better than Base Damage
  - This is more of a design decision than anything. While I get you may want to build it on Jhin, not every item has to be good on every character. Take backup mags for example, they can be broken on Artificer, but useless on Commando. If the item always get turned into scrap then that's a bad thing, but if it's situational then I think it's okay. It also opens the item up for different synergies, like procing a lot on huntress' ult.
  - Also, as @knightmare013 mentioned, the damage was bugged as it wasn't scaling from stacking it which may also influence those numbers. This will be fixed shortly.
- Give an icon to indicate when the next proc will be up
  - After reading this, I realized I implemented the damage incorrectly, which would have made the icon not as useful. I copied the code from BorK, so the counting was for each individual enemy. That means you'd get damage after hitting the same enemy 3 times rather than being able to switch targets. I will change this so it functions more similar to league when the stacking is on you, and will add the icon at the same time.

**Comment by 06Kioshi** [comment] 2023-10-08 05:14
Thank you for the quick response!

Totally get it being a design choice, whenever the damage is unbugged I'll have to try it on huntress.

And if your code is already oriented to having the stacks on each induvial enemy, you could instead display a "debuff" that showed how many more hits it would require for Kraken to proc on said enemy.

**Comment by Debonairesnake6** [comment] 2023-10-08 06:14
Pushing out the update now. I've updated the code so you can hit any 3 enemies, rather than requiring you to hit the same target. Also, I added the visual indicator, but I'm not in love with it. Even practising with 2 polylutes and 2 shrimps vs a single enemy causes it to freak out a bit and not be too useful. Play around with it and let me know what you think, but I think later in the game this would be kinda useless since there is no cooldown and it'll constantly cycle. I might remove this in the future if it provides no benefit past stage 2-3.

Regarding your suggestion around the visual debuff on enemies I specifically did not want to do that, as I didn't want to cause confusion with Death Mark. I don't think this should count towards Death Mark debuff stacks since a stack alone doesn't do anything, but if you can see it then people would think it would. Also, having a small number increment as enemies jump around would be a nightmare to follow properly.

**Closed** 2023-10-08 06:15 UTC
