### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by XileHD** [Debonairesnake6/LoLItems#36] opened 2023-11-22 05:50 UTC
My friends and I have been crashing recently when dropping "Kraken Slayer" to each other using the "/drop item mod" it also crashed at times when Mythrix would grab our items and Kraken Slayer would be one of them. If you can please look into it to try and fix it that would be awesome. Thank you.

**Comment by Debonairesnake6** [comment] 2023-11-22 12:44
I'll look into fixing whatever may be causing that. In the meantime you can modify the config settings of the mod to disable kraken slayer until I get it fixed.

**Comment by XileHD** [comment] 2023-11-22 16:57
okay, sounds good thank you!

**Comment by ggreer91** [comment] 2023-11-22 21:40
Hey @XileHD! Would you be willing to send me your Thunderstore profile code? And have you been able to reproduce this crash with Mithrix? If so, could you reproduce it, save your logs from that game, and post it here?

**Comment by ggreer91** [comment] 2023-11-22 21:41
Hey @XileHD! Would you be willing to post your Thunderstore profile code? And have you been able to reproduce this crash with Mithrix? If so, could you reproduce it, save your logs from that game, and post it here?

**Comment by ggreer91** [comment] 2023-11-22 21:43
Hey @XileHD! Would you be willing to post your Thunderstore profile code? And have you been able to reproduce this crash with Mithrix? If so, could you reproduce it, save your logs from that game, and post it here?

Thank you!

**Comment by XileHD** [comment] 2023-11-23 02:53
This is the code "018bfa13-21b2-5f35-5710-8cce2d8d4dcd".  The Crash with Mithrix happened twice but I believe the crash happens because of the item being dropped. When I would drop "Kraken Slayer" to a friend they would crash and sometimes even when they would drop it but this crash happened a handful of times so we just turned off the item for now. I also don't know how to check or save logs, so maybe you test it out for me.

**Comment by ggreer91** [comment] 2023-11-27 19:11
Hey! I've been testing out your profile over the past few days and was unable to reproduce the bug. Would you be free to do a run with me so we can test it out together? If so, feel free to add me on discord and we can set up a time, my username is "mangostyles"!

**Comment by ggreer91** [comment] 2023-11-27 19:12
> This is the code "018bfa13-21b2-5f35-5710-8cce2d8d4dcd". The Crash with Mithrix happened twice but I believe the crash happens because of the item being dropped. When I would drop "Kraken Slayer" to a friend they would crash and sometimes even when they would drop it but this crash happened a handful of times so we just turned off the item for now. I also don't know how to check or save logs, so maybe you test it out for me.

Hey! I've been testing out your profile over the past few days and was unable to reproduce the bug. Would you be free to do a run with me so we can test it out together? If so, feel free to add me on discord and we can set up a time, my username is "mangostyles"!

**Comment by Debonairesnake6** [comment] 2023-12-19 00:21
@XileHD I think we've tracked down and fixed the issue. It should be resolved in the update we will release shortly. Sorry for the delay on this, it was difficult to replicate at first.

**Comment by XileHD** [comment] 2023-12-19 00:32
> @XileHD I think we've tracked down and fixed the issue. It should be resolved in the update we will release shortly. Sorry for the delay on this, it was difficult to replicate at first.

Awesome! sorry for the hassle

**Comment by Debonairesnake6** [comment] 2023-12-19 00:42
@XileHD not at all! A bug like this is something we'd never find from testing alone in our testing worlds so unless people like you report it then it'd be broken without our knowledge.

In case you are interested, here is a simplified version of how the crash occurred:

- In our mod items modify your stats, but it didn't check if you were the host of the game or a client connecting to it.
- If you are a client connecting to a game, you can't do certain things like remove buffs on a character. The host calculates that for you then sends you the updated information for the client to use.
- In this case, when a client drop/removed Kraken Slayer it would try and remove the buff stacks one at a time (this is just how the game works) until they no longer had any stacks left. Since the client can't remove buffs, it would get stuck in an infinite loop and hang the game which caused it to crash.

Now with all of this being said, I'm assuming that when these crashes happened it was only ever the client crashing, the host seemed to be unaffected during our test. If that is not the case let us know and we can see if something else that's funky is going on.

**Comment by XileHD** [comment] 2023-12-19 00:45
> @XileHD not at all! A bug like this is something we'd never find from testing alone in our testing worlds so unless people like you report it then it'd be broken without our knowledge.
> 
> In case you are interested, here is a simplified version of how the crash occurred:
> 
> * In our mod items modify your stats, but it didn't check if you were the host of the game or a client connecting to it.
> * If you are a client connecting to a game, you can't do certain things like remove buffs on a character. The host calculates that for you then sends you the updated information for the client to use.
> * In this case, when a client drop/removed Kraken Slayer it would try and remove the buff stacks one at a time (this is just how the game works) until they no longer had any stacks left. Since the client can't remove buffs, it would get stuck in an infinite loop and hang the game which caused it to crash.
> 
> Now with all of this being said, I'm assuming that when these crashes happened it was only ever the client crashing, the host seemed to be unaffected during our test. If that is not the case let us know and we can see if something else that's funky is going on.

Thank you for the information and yes you are 100% correct since I always hosted I never crashed to Kraken being dropped, only my friends would.

**Closed** 2023-12-19 02:31 UTC
